CREATE TABLE staging.d_indicator_metadata (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source              VARCHAR(10) NOT NULL,
    indicator_name      VARCHAR(255) NOT NULL,
    unit                VARCHAR(50),
    aggregate_code      INT,
    variable_code       INT,
    category_code       INT,
    query_start_date    DATE,
    query_end_date      DATE,
    endpoint_reference  TEXT
);

