CREATE TABLE staging.f_indicator_value (

    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    indicator_id        INT NOT NULL,
    reference_date      DATE NOT NULL,

    value               NUMERIC(18,6) NOT NULL,

    geographic_code     VARCHAR(20),

    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_indicator
        FOREIGN KEY (indicator_id)
        REFERENCES staging.d_indicator_metadata (id)
);
